repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # Use the latest version
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 24.3.0 # Use a recent version compatible with your pyproject.toml
    hooks:
    -   id: black

-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2 # Use a recent version compatible with your pyproject.toml
    hooks:
    -   id: isort

-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0 # Use a recent version
    hooks:
    -   id: flake8
        args: ['--max-line-length=88']
        additional_dependencies: [
            "flake8-bugbear>=23.0.0",
            "flake8-comprehensions>=3.10.0",
            "flake8-print>=5.0.0"
        ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0 # Use a recent version
    hooks:
    -   id: mypy
        args: [--config-file=pyproject.toml] # Ensure it reads pyproject.toml
        additional_dependencies: [
            "pydantic>=2.0.0",
            "types-aiofiles"
        ]
